// Generated by CoffeeScript 1.3.3

$(function() {
  var methods;
  methods = {
    init: function() {
      $(this).snPlayer('onClickPlay');
      return $(this).snPlayer('onClickclose');
    },
    onClickclose: function() {
      return $("#player-close").on("click", function(e) {
        e.prevEventDefault();
        return $("#player-wrap").hide();
      });
    },
    onClickPlay: function() {
      return $("a.play").on("click", function(e) {
        var id, src;
        e.prevEventDefault();
        id = $(this).data('id');
        src = $(this).data('src');
        $("#player-wrap").show();
        $("#player").html('<audio/>'.data('id', id));
        return audiojs.events.ready(function() {
          var a, audio;
          a = audiojs.createAll();
          audio = a[0];
          $("#player-close").on("click", function(e) {
            e.prevEventDefault();
            audio.pause();
            return $("#player").html('');
          });
          audio.load(src);
          return audio.play();
        });
      });
    }
  };
  return $.fn.snPlayer = function(sn) {
    if (!sn) {
      sn = {};
    }
    if (methods[sn]) {
      return methods[sn].apply(this, Array.prototype.slice.call(arguments, 1));
    } else {
      if (typeof sn === 'object' || !sn) {
        return methods.init.apply(this, arguments);
      } else {
        return $.error('Метод ' + sn + ' не существует');
      }
    }
  };
});
